#name: Update Cloudflare DNS (Type A)
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  update-cloudflare-dns:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Update Cloudflare DNS (Type A)
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          CLOUDFLARE_ZONE_ID: 8daf5dfd27c4efe086b3b6d1eaaea4df
#          DOMAIN: karazo.com
#          IP_ADDRESS: 104.21.18.239
#        run: |
#          curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records" \
#          -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
#          -H "Content-Type: application/json" \
#          --data '{
#            "type": "A",
#            "name": "'"$DOMAIN"'",
#            "content": "'"$IP_ADDRESS"'",
#            "ttl": 1,
#            "proxied": true
#          }'
